ts       = 2048       # Ensures the cryptographic key meets at least 128-bit security
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
C  = US                                  # Country
ST = Tennessee                           # State
L  = Knoxville                           # Locality
O  = University of Tennessee             # Organization
OU = Department of Electrical Engineering and Computer Science  # Organizational Unit
CN = Connor Riley                         # Common Name (Your Name)
uid = criley16                      # User ID (Your NetID)

